### ISSUE TITLE
使用slack作为后端，一直报错

### ISSUE THREAD

**Issue by bubbleatgit** [fleeto/issueflow#2]
描述：
      容器启动环境变量指定了backend为slack，token已配置，但是docker启动后一直提示错误：

```
chatbot_1  | 2019-03-06 10:13:58,621 INFO     errbot.bootstrap          Found Backend plugin: 'Slack'
chatbot_1  | 						Description: This is the slack backend for Err.
chatbot_1  | 2019-03-06 10:13:59,348 INFO     errbot                    webhooks:  Flag to bind /echo to                           echo
chatbot_1  | 2019-03-06 10:13:59,379 INFO     errbot.backends.slack     Verifying authentication token
chatbot_1  | 2019-03-06 10:13:59,815 ERROR    errbot.backends.base      Exception occurred in serve_once:
chatbot_1  | Traceback (most recent call last):
chatbot_1  |   File "/usr/lib/python3.6/site-packages/errbot/backends/base.py", line 686, in serve_forever
chatbot_1  |     if self.serve_once():
chatbot_1  |   File "/usr/lib/python3.6/site-packages/errbot/backends/slack.py", line 371, in serve_once
chatbot_1  |     raise SlackAPIResponseError(error="Couldn't authenticate with Slack. Server said: %s" % self.auth['error'])
chatbot_1  | yapsy_loaded_plugin_Slack_0.SlackAPIResponseError
chatbot_1  | 2019-03-06 10:13:59,818 INFO     errbot.backends.base      Reconnecting in 1 seconds (0 attempted reconnections so far)
chatbot_1  | 2019-03-06 10:14:00,819 INFO     errbot.backends.slack     Verifying authentication token
chatbot_1  | 2019-03-06 10:14:01,168 ERROR    errbot.backends.base      Exception occurred in serve_once:
```

请大佬指定下

**Comment by fleeto** [comment]
启动脚本看看？

**Comment by bubbleatgit** [comment]
> 启动脚本看看？

找到问题了，token的值不能带各种引号，要把token直接写进去
